function inicial(){
let imagem1 = document.getElementById("img1").src = "assets/item-1.jpeg"
let imagem2 = document.getElementById("img2").src = "assets/item-2.jpeg"
let imagem3 = document.getElementById("img3").src = "assets/item-3.jpeg"
let imagem4 = document.getElementById("img4").src = "assets/item-4.jpeg"
let imagem5 = document.getElementById("img5").src = "assets/item-5.jpeg"
let imagem6 = document.getElementById("img6").src = "assets/item-6.jpeg"
let imagem7 = document.getElementById("img7").src = "assets/item-7.jpeg"
let imagem8 = document.getElementById("img8").src = "assets/item-8.jpeg"
let imagem9 = document.getElementById("img9").src = "assets/item-9.jpeg"
let imagem10 = document.getElementById("img10").src = "assets/item-10.jpeg"
let name1 = document.getElementById("nome1").innerHTML = "Buttermilk Pancakes"
let name2 = document.getElementById("nome2").innerHTML = "Godzilla Milkshake"
let name3 = document.getElementById("nome3").innerHTML = "Godzilla Milkshake"
let name4 = document.getElementById("nome4").innerHTML = "Bacon Overflow"
let name5 = document.getElementById("nome5").innerHTML = "Quarantine Buddy"
let name6 = document.getElementById("nome6").innerHTML = "Quarantine Buddy"
let name7 = document.getElementById("nome7").innerHTML = "Country Delight"
let name8 = document.getElementById("nome8").innerHTML = "Oreo Dream"
let name9 = document.getElementById("nome9").innerHTML = "Bison Steak"
let name10 = document.getElementById("nome10").innerHTML = "Bison Steak"
let value1 = document.getElementById("valor1").innerHTML = "$15.99"
let value2 = document.getElementById("valor2").innerHTML = "$6.99"
let value3 = document.getElementById("valor3").innerHTML = "$22.99"
let value4 = document.getElementById("valor4").innerHTML = "$8.99"
let value5 = document.getElementById("valor5").innerHTML = "$16.99"
let value6 = document.getElementById("valor6").innerHTML = "$13.99"
let value7 = document.getElementById("valor7").innerHTML = "$20.99"
let value8 = document.getElementById("valor8").innerHTML = "$18.99"
let value9 = document.getElementById("valor9").innerHTML = "$12.99"
let value10 = document.getElementById("valor10").innerHTML = "$22.99"
let text1 = document.getElementById("texto1").innerHTML = "I'm baby woke mlkshk wolf bitters live-edge<br> blue bottle, hammock freegan copper<br> mug whatever cold-pressed"
let text2 = document.getElementById("texto2").innerHTML = "ombucha chillwave fanny pack 3 wolf<br> moon street art photo booth before they<br> sold out organic viral."
let text3 = document.getElementById("texto3").innerHTML = "franzen vegan pabst bicycle rights<br> kickstarter pinterest meditation<br> farm-to-table 90's pop-up"
let text4 = document.getElementById("texto4").innerHTML = "I'm baby woke mlkshk wolf bitters<br> live-edge blue bottle, hammock freegan<br> copper mug whatever cold-pressed<"
let text5 = document.getElementById("texto5").innerHTML = "skateboard fam synth authentic semiotics.<br> Live-edge lyft af, edison bulb yuccie<br> crucifix microdosing."
let text6 = document.getElementById("texto6").innerHTML = "vaporware iPhone<br> mumblecore selvage raw<br> denim slow-carb leggings<br> gochujang helvetica man<br> braid jianbing. Marfa thundercats"
let text7 = document.getElementById("texto7").innerHTML = "Shabby chic keffiyeh neutra snackwave<br> pork belly shoreditch. Prism<br> austin mlkshk truffaut,"
let text8 = document.getElementById("texto8").innerHTML = "Portland chicharrones ethical edison<br> bulb, palo santo craft beer chia<br> heirloom iPhone everyday"
let text9 = document.getElementById("texto9").innerHTML = "on it tumblr kickstarter thundercats<br> migas everyday carry squid palo<br> santo leggings. Food truck truffaut"
let text10 = document.getElementById("texto10").innerHTML = "skateboard fam synth authentic semiotics.<br> Live-edge lyft af, edison bulb yuccie<br> crucifix microdosing."
}

function jantar(){
todos()
apagado()
let opacidadea = document.getElementById("img1").style.opacity = "100%"
let opacidaded = document.getElementById("nome1").style.opacity = "100%"
let opacidadeg = document.getElementById("valor1").style.opacity = "100%"
let opacidadek = document.getElementById("texto1").style.opacity = "100%"
let line1 = document.getElementById("linha1").style. opacity = "100"

let imagem1 = document.getElementById("img1").src = "assets/item-10.jpeg"
let name1 = document.getElementById("nome1").innerHTML = "Bison Steak"
let value1 = document.getElementById("valor1").innerHTML = "$22.99"
let text1 = document.getElementById("texto1").innerHTML = "skateboard fam synth authentic semiotics.<br> Live-edge lyft af, edison bulb yuccie<br> crucifix microdosing."

}

function bebida(){
todos()
apagado()
let opacidadea = document.getElementById("img1").style.opacity = "100%"
let opacidadeb = document.getElementById("img2").style.opacity = "100%"
let opacidadec = document.getElementById("img6").style.opacity = "100%"
let opacidaded = document.getElementById("nome1").style.opacity = "100%"
let opacidadee = document.getElementById("nome2").style.opacity = "100%"
let opacidadef = document.getElementById("nome6").style.opacity = "100%"
let opacidadeg = document.getElementById("valor1").style.opacity = "100%"
let opacidadeh = document.getElementById("valor2").style.opacity = "100%"
let opacidadej = document.getElementById("valor6").style.opacity = "100%"
let opacidadek = document.getElementById("texto1").style.opacity = "100%"
let opacidadel = document.getElementById("texto2").style.opacity = "100%"
let opacidadem = document.getElementById("texto6").style.opacity = "100%"
let line1 = document.getElementById("linha1").style. opacity = "100"
let line2 = document.getElementById("linha2").style. opacity = "100"
let line3 = document.getElementById("linha6").style. opacity = "100"


let imagem1 = document.getElementById("img1").src = "assets/item-3.jpeg"
let imagem2 = document.getElementById("img2").src = "assets/item-9.jpeg"
let imagem6 = document.getElementById("img6").src = "assets/item-6.jpeg"
let name1 = document.getElementById("nome1").innerHTML = "Godzilla Milkshake"
let name2 = document.getElementById("nome2").innerHTML = "Bison Steak"
let name6 = document.getElementById("nome6").innerHTML = "Quarantine Buddy"
let value1 = document.getElementById("valor1").innerHTML = "$22.99"
let value2 = document.getElementById("valor2").innerHTML = "$12.99"
let value6 = document.getElementById("valor6").innerHTML = "$13.99"
let text1 = document.getElementById("texto1").innerHTML = "franzen vegan pabst bicycle rights<br> kickstarter pinterest meditation<br> farm-to-table 90's pop-up"
let text2 = document.getElementById("texto2").innerHTML = "on it tumblr kickstarter thundercats<br> migas everyday carry squid palo<br> santo leggings. Food truck truffaut"
let text6 = document.getElementById("texto6").innerHTML = "vaporware iPhone<br> mumblecore selvage raw<br> denim slow-carb leggings<br> gochujang helvetica man<br> braid jianbing. Marfa thundercats"
}


function almoco() {
	todos()
	apagado()
let opacidadea = document.getElementById("img1").style.opacity = "100%"
let opacidadeb = document.getElementById("img2").style.opacity = "100%"
let opacidadec = document.getElementById("img6").style.opacity = "100%"
let opacidaded = document.getElementById("nome1").style.opacity = "100%"
let opacidadee = document.getElementById("nome2").style.opacity = "100%"
let opacidadef = document.getElementById("nome6").style.opacity = "100%"
let opacidadeg = document.getElementById("valor1").style.opacity = "100%"
let opacidadeh = document.getElementById("valor2").style.opacity = "100%"
let opacidadei = document.getElementById("valor6").style.opacity = "100%"
let opacidadej = document.getElementById("texto1").style.opacity = "100%"
let opacidadek = document.getElementById("texto2").style.opacity = "100%"
let opacidadel = document.getElementById("texto6").style.opacity = "100%"
let line1 = document.getElementById("linha1").style. opacity = "100"
let line2 = document.getElementById("linha2").style. opacity = "100"
let line6 = document.getElementById("linha6").style. opacity = "100"


let imagem1 = document.getElementById("img1").src = "assets/item-2.jpeg"
let imagem2 = document.getElementById("img2").src = "assets/item-8.jpeg"
let imagem6 = document.getElementById("img6").src = "assets/item-5.jpeg"
let name1 = document.getElementById("nome1").innerHTML = "Godzilla Milkshake"
let name2 = document.getElementById("nome2").innerHTML = "Oreo Dream"
let name6 = document.getElementById("nome6").innerHTML = "Quarantine Buddy"
let value1 = document.getElementById("valor1").innerHTML = "$8.99"
let value2 = document.getElementById("valor2").innerHTML = "$18.99"
let value6 = document.getElementById("valor6").innerHTML = "$16.99"
let text1 = document.getElementById("texto1").innerHTML = "ombucha chillwave fanny pack 3 wolf<br> moon street art photo booth before they<br> sold out organic viral."
let text2 = document.getElementById("texto2").innerHTML = "Portland chicharrones ethical edison<br> bulb, palo santo craft beer chia<br> heirloom iPhone everyday"
let text6 = document.getElementById("texto6").innerHTML = "skateboard fam synth authentic semiotics.<br> Live-edge lyft af, edison bulb yuccie<br> crucifix microdosing."
}




function apagado(argument) {
let imagem1 = document.getElementById("img1").style.opacity = "0%"
let imagem2 = document.getElementById("img2").style.opacity = "0%"
let imagem3 = document.getElementById("img3").style.opacity = "0%"
let imagem4 = document.getElementById("img4").style.opacity = "0%"
let imagem5 = document.getElementById("img5").style.opacity = "0%"
let imagem6 = document.getElementById("img6").style.opacity = "0%"
let imagem7 = document.getElementById("img7").style.opacity = "0%"
let imagem8 = document.getElementById("img8").style.opacity = "0%"
let imagem9 = document.getElementById("img9").style.opacity = "0%"
let imagem10 = document.getElementById("img10").style.opacity = "0%"
let name1 = document.getElementById("nome1").style.opacity = "0%"
let name2 = document.getElementById("nome2").style.opacity = "0%"
let name3 = document.getElementById("nome3").style.opacity = "0%"
let name4 = document.getElementById("nome4").style.opacity = "0%"
let name5 = document.getElementById("nome5").style.opacity = "0%"
let name6 = document.getElementById("nome6").style.opacity = "0%"
let name7 = document.getElementById("nome7").style.opacity = "0%"
let name8 = document.getElementById("nome8").style.opacity = "0%"
let name9 = document.getElementById("nome9").style.opacity = "0%"
let name10 = document.getElementById("nome10").style.opacity = "0%"
let value1 = document.getElementById("valor1").style.opacity = "0%"
let value2 = document.getElementById("valor2").style.opacity = "0%"
let value3 = document.getElementById("valor3").style.opacity = "0%"
let value4 = document.getElementById("valor4").style.opacity = "0%"
let value5 = document.getElementById("valor5").style.opacity = "0%"
let value6 = document.getElementById("valor6").style.opacity = "0%"
let value7 = document.getElementById("valor7").style.opacity = "0%"
let value8 = document.getElementById("valor8").style.opacity = "0%"
let value9 = document.getElementById("valor9").style.opacity = "0%"
let value10 = document.getElementById("valor10").style.opacity = "0%"
let text1 = document.getElementById("texto1").style.opacity = "0%"
let text2 = document.getElementById("texto2").style.opacity = "0%"
let text3 = document.getElementById("texto3").style.opacity = "0%"
let text4 = document.getElementById("texto4").style.opacity = "0%"
let text5 = document.getElementById("texto5").style.opacity = "0%"
let text6 = document.getElementById("texto6").style.opacity = "0%"
let text7 = document.getElementById("texto7").style.opacity = "0%"
let text8 = document.getElementById("texto8").style.opacity = "0%"
let text9 = document.getElementById("texto9").style.opacity = "0%"
let text10 = document.getElementById("texto10").style.opacity = "0%"
let line1 = document.getElementById("linha1").style. opacity = "0"
let line2 = document.getElementById("linha2").style. opacity = "00"
let line3 = document.getElementById("linha3").style. opacity = "0"
let line4 = document.getElementById("linha4").style. opacity = "0"
let line5 = document.getElementById("linha5").style. opacity = "0"
let line6 = document.getElementById("linha6").style. opacity = "0"
let line7 = document.getElementById("linha7").style. opacity = "0"
let line8 = document.getElementById("linha8").style. opacity = "0"
let line9 = document.getElementById("linha9").style. opacity = "0"
let line10 = document.getElementById("linha10").style. opacity = "0"
}

function todos(){
inicial()
let imagem1 = document.getElementById("img1").style.opacity = "100%"
let imagem2 = document.getElementById("img2").style.opacity = "100%"
let imagem3 = document.getElementById("img3").style.opacity = "100%"
let imagem4 = document.getElementById("img4").style.opacity = "100%"
let imagem5 = document.getElementById("img5").style.opacity = "100%"
let imagem6 = document.getElementById("img6").style.opacity = "100%"
let imagem7 = document.getElementById("img7").style.opacity = "100%"
let imagem8 = document.getElementById("img8").style.opacity = "100%"
let imagem9 = document.getElementById("img9").style.opacity = "100%"
let imagem10 = document.getElementById("img10").style.opacity = "100%"
let name1 = document.getElementById("nome1").style.opacity = "100%"
let name2 = document.getElementById("nome2").style.opacity = "100%"
let name3 = document.getElementById("nome3").style.opacity = "100%"
let name4 = document.getElementById("nome4").style.opacity = "100%"
let name5 = document.getElementById("nome5").style.opacity = "100%"
let name6 = document.getElementById("nome6").style.opacity = "100%"
let name7 = document.getElementById("nome7").style.opacity = "100%"
let name8 = document.getElementById("nome8").style.opacity = "100%"
let name9 = document.getElementById("nome9").style.opacity = "100%"
let name10 = document.getElementById("nome10").style.opacity = "100%"
let value1 = document.getElementById("valor1").style.opacity = "100%"
let value2 = document.getElementById("valor2").style.opacity = "100%"
let value3 = document.getElementById("valor3").style.opacity = "100%"
let value4 = document.getElementById("valor4").style.opacity = "100%"
let value5 = document.getElementById("valor5").style.opacity = "100%"
let value6 = document.getElementById("valor6").style.opacity = "100%"
let value7 = document.getElementById("valor7").style.opacity = "100%"
let value8 = document.getElementById("valor8").style.opacity = "100%"
let value9 = document.getElementById("valor9").style.opacity = "100%"
let value10 = document.getElementById("valor10").style.opacity = "100%"
let text1 = document.getElementById("texto1").style.opacity = "100%"
let text2 = document.getElementById("texto2").style.opacity = "100%"
let text3 = document.getElementById("texto3").style.opacity = "100%"
let text4 = document.getElementById("texto4").style.opacity = "100%"
let text5 = document.getElementById("texto5").style.opacity = "100%"
let text6 = document.getElementById("texto6").style.opacity = "100%"
let text7 = document.getElementById("texto7").style.opacity = "100%"
let text8 = document.getElementById("texto8").style.opacity = "100%"
let text9 = document.getElementById("texto9").style.opacity = "100%"
let text10 = document.getElementById("texto10").style.opacity = "100%"
let line1 = document.getElementById("linha1").style. opacity = "100%"
let line2 = document.getElementById("linha2").style. opacity = "100%"
let line3 = document.getElementById("linha3").style. opacity = "100%"
let line4 = document.getElementById("linha4").style. opacity = "100%"
let line5 = document.getElementById("linha5").style. opacity = "100%"
let line6 = document.getElementById("linha6").style. opacity = "100%"
let line7 = document.getElementById("linha7").style. opacity = "100%"
let line8 = document.getElementById("linha8").style. opacity = "100%"
let line9 = document.getElementById("linha9").style. opacity = "100%"
let line10 = document.getElementById("linha10").style. opacity = "100%"
}

function manha(){
	inicial()

let line1 = document.getElementById("linha1").style. opacity = "100"
let line2 = document.getElementById("linha2").style. opacity = "100"
let line3 = document.getElementById("linha6").style. opacity = "100"
let line4 = document.getElementById("linha4").style. opacity = "0"
let line5 = document.getElementById("linha5").style. opacity = "0"
let line6 = document.getElementById("linha6").style. opacity = "0"
let line7 = document.getElementById("linha7").style. opacity = "0"
let line8 = document.getElementById("linha8").style. opacity = "0"
let line9 = document.getElementById("linha9").style. opacity = "0"
let line10 = document.getElementById("linha10").style. opacity = "0"
let imagem1 = document.getElementById("img1").src = "assets/item-1.jpeg"
let imagem2 = document.getElementById("img2").src = "assets/item-7.jpeg"
let imagem3 = document.getElementById("img3").style.opacity = "0"
let imagem4 = document.getElementById("img4").style.opacity = "0"
let imagem5 = document.getElementById("img5").style.opacity = "0"
let imagem6 = document.getElementById("img6").src = "assets/item-4.jpeg"
let imagem7 = document.getElementById("img7").style.opacity = "0"
let imagem8 = document.getElementById("img8").style.opacity = "0"
let imagem9 = document.getElementById("img9").style.opacity = "0"
let imagem10 = document.getElementById("img10").style.opacity = "0"
let name1 = document.getElementById("nome1").innerHTML = "Buttermilk Pancakes"
let name2 = document.getElementById("nome2").innerHTML = "Country Delight"
let name3 = document.getElementById("nome3").style.opacity = "0"
let name4 = document.getElementById("nome4").style.opacity = "0"
let name5 = document.getElementById("nome5").style.opacity = "0"
let name6 = document.getElementById("nome6").innerHTML = "Bacon Overflow"
let name7 = document.getElementById("nome7").style.opacity = "0"
let name8 = document.getElementById("nome8").style.opacity = "0"
let name9 = document.getElementById("nome9").style.opacity = "0"
let name10 = document.getElementById("nome10").style.opacity = "0"
let value1 = document.getElementById("valor1").innerHTML = "$15.99"
let value2 = document.getElementById("valor2").innerHTML = "$20.99"
let value3 = document.getElementById("valor3").style.opacity = "0"
let value4 = document.getElementById("valor4").style.opacity = "0"
let value5 = document.getElementById("valor5").style.opacity = "0"
let value6 = document.getElementById("valor6").innerHTML = "$8.99"
let value7 = document.getElementById("valor7").style.opacity = "0"
let value8 = document.getElementById("valor8").style.opacity = "0"
let value9 = document.getElementById("valor9").style.opacity = "0"
let value10 = document.getElementById("valor10").style.opacity = "0"
let text1 = document.getElementById("texto1").innerHTML = "I'm baby woke mlkshk wolf bitters live-edge<br> blue bottle, hammock freegan copper<br> mug whatever cold-pressed"
let text2 = document.getElementById("texto2").innerHTML = "Shabby chic keffiyeh neutra snackwave<br> pork belly shoreditch. Prism<br> austin mlkshk truffaut,"
let text3 = document.getElementById("texto3").style.opacity = "0"
let text4 = document.getElementById("texto4").style.opacity = "0"
let text5 = document.getElementById("texto5").style.opacity = "0"
let text6 = document.getElementById("texto6").innerHTML = "I'm baby woke mlkshk wolf bitters<br> live-edge blue bottle, hammock freegan<br> copper mug whatever cold-pressed<"
let text7 = document.getElementById("texto7").style.opacity = "0"
let text8 = document.getElementById("texto8").style.opacity = "0"
let text9 = document.getElementById("texto9").style.opacity = "0"
let text10 = document.getElementById("texto10").style.opacity = "0"
}


